config/routes.rb
Rails.application.routes.draw do
  root 'organizations#index'
  resources :organizations, only: [:index, :show] do
    resources :ratings, shallow: true, except: [:destroy, :index]
  end

end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  id            :integer          not null, primary key
#  name          :string
#  size          :string
#  org_type      :string
#  address       :string
#  city          :string
#  zip           :integer
#  county        :string
#  state         :string
#  latitude      :float
#  longitude     :float
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  ratings_count :integer
#

class Organization < ActiveRecord::Base
  has_many :ratings, inverse_of: :organization, dependent: :delete_all
  # validates_associated :ratings
end

app/models/rating.rb
# == Schema Information
#
# Table name: ratings
#
#  id              :integer          not null, primary key
#  user_name       :string
#  score           :decimal(3, 1)
#  comment         :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  organization_id :integer
#

class Rating < ActiveRecord::Base
  belongs_to :organization, -> { readonly },
                            inverse_of: :ratings,
                            foreign_key: 'organization_id'

  validates :user_name, presence: { message: 'Your preferred name to display must be given' },
                        length: { maximum: 12,
                                  message: 'Your user name should be shorter than 12 letters' }

  validates :score, presence: { message: 'You must specify a score on this organization' },
                     numericality: { greater_than_or_equal_to:0,
                                     less_than_or_equal_to:10,
                                     message: 'The score should range 0 - 10' }

  validates :comment, length: { maximum: 300,
                                message: 'Please comment within 300 words' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def index
    @organizations = Organization.all
    js :organizations => @organizations
  end# end of a method

  def show
    @organization = Organization.find(params[:id])
    @ratings = @organization.ratings
    # The average rating of this organization, rounded to the nearest 10th
    @average = avg_ratings_cal(@ratings)
    # The most recent non-empty comment on this organization
    @comment = recent_comment(@ratings)
    # Three restaurants in 1500 meters radius of this organization from yelp_token
    @restaurants = find_yelp_business(@organization[:latitude], @organization[:longitude], 'restaurants')
    @bars = find_yelp_business(@organization[:latitude], @organization[:longitude], 'bars')
    #the paloma gem uses this to pass variables from contoller to javascript
    js :organization => @organization, :restaurants => @restaurants, :bars => @bars
  end# end of a method



  private
    def avg_ratings_cal(ratings)
      ratings.pluck(:score).empty? ? 'No ratings yet. Be the first to rate it!' : ratings.average(:score).round(1)
    end# end of method

    def recent_comment(ratings)
      if ratings.pluck(:comment).empty?
        'No comments yet. Be the first to leave a comment!'
      else
        comments = ratings.pluck(:comment).reverse
        comments.select! do |element|
          element != ''
        end
        comments.first
      end
    end# end of method

    def find_yelp_business(lat, lng, type)
      # the yelp token is set to an environment variable
      header = "Bearer " + ENV['YELP_TOKEN']
      url = 'https://api.yelp.com/v3/businesses/search?latitude=' + lat.to_s + '&longitude=' + lng.to_s + "&radius=1500&limit=10&categories=#{type}"
      open(url, "Authorization" => header) do |f|
        query_result_string = f.read
        query_result_json = JSON.parse(query_result_string)
        return query_result_json
      end
    end# end of method

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update]

  # the index action is restricted by the routing
  # GET /ratings
  # GET /ratings.json
  # def index
  #   @ratings = Rating.all
  # end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @organization = Organization.find(params[:organization_id])
    @rating = @organization.ratings.build
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @organization = Organization.find(params[:organization_id])
    @rating = @organization.ratings.build(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # the delete action is restricted by routing
  # DELETE /ratings/1
  # DELETE /ratings/1.json
  # def destroy
  #   @rating.destroy
  #   respond_to do |format|
  #     format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:user_name, :score, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Source+Serif+Pro:700' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0 maximum-scale=1, user-scalable=no">
    <title><%= content_for?(:title) ? yield(:title) : "L.A." %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <!-- Import the Stamen Toner -->
    <%= javascript_include_tag 'http://maps.stamen.com/js/tile.stamen.js?v1.3.0' %>
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <div class="header">
      <h1>Arts & Cultural Organizations in L.A.</h1>
    </div>

    <div class="content">
      <%= bootstrap_flash %>
      <%= yield %>
      <%= insert_paloma_hook %>
    </div>

  </body>
</html>

app/views/organizations/_legend.html.erb
<table class='org-legend'>
  <col width="20px">
  <col width="250px">
  <tr>
    <td><div id='legend-education'></div></td>
    <td>Education</td>
  </tr>
  <tr>
    <td><div id='legend-community'></div></td>
    <td>Community</td>
  </tr>
  <tr>
    <td><div id='legend-performing'></div></td>
    <td>Performing Arts</td>
  </tr>
  <tr>
    <td><div id='legend-support'></div></td>
    <td>Support and Advocacy</td>
  </tr>
  <tr>
    <td><div id='legend-collecting'></div></td>
    <td>Collecting, Curating, and Exibiting</td>
  </tr>
  <tr>
    <td><div id='legend-broadcast'></div></td>
    <td>Broadcast, Literary, and Media Arts</td>
  </tr>
</table>

app/views/organizations/index.html.erb
<div id='map-all-orgs'></div>

<div class="sidebar-all-orgs">
  <form id='form-org-search'>
    <div id='div-searchbox'><input type="text" placeholder="Organization Name..." id='searchbox-org-name'></div>
    <div><input type="button" value="Search" id='btn-org-search'></div>
    <div><input type='button' value='Clear' id='btn-org-clear'></div>
  </form>
  <hr>
  <table id=tbl-heatmap>
    <tr>
      <td><h4>Heat Map</h4></td>
      <td>
        <div id='div-heatmap-ckbox'>
          <input type="checkbox" name="heatmap" value="heatmap" id='ckbox-heatmap' unchecked>
          <label for='ckbox-heatmap'></label>
        </div>
      </td>
    </tr>
  </table>
  <hr>
  <div id='div-switches'>
    <table class='switch-tbl' id='tbl-switch'>
      <tr><td>Display by Type</td>
          <td><label class="switch"><input type="checkbox" id='swith-type' unchecked><div class="slider round"></div></label></td>
          <td>Display by Size</td>
          <td><label class="switch"><input type="checkbox" id='swith-size' unchecked><div class="slider round"></div></label></td></tr>
    </tabel>
    <table class='switch-tbl' id='tbl-org-type-switch'>
      <tr><td>Education</td>
          <td><label class="switch"><input type="checkbox" id='swith-edu' unchecked><div class="slider"></div></label></td>
          <td>Community</td>
          <td><label class="switch"><input type="checkbox" id='swith-com' unchecked><div class="slider"></div></label></td></tr>
      <tr><td>Performing Arts</td>
          <td><label class="switch"><input type="checkbox" id='swith-per' unchecked><div class="slider"></div></label></td>
          <td>Support & Advocacy</td>
          <td><label class="switch"><input type="checkbox" id='swith-sup' unchecked><div class="slider"></div></label></td></tr>
      <tr><td>Museums</td>
          <td><label class="switch"><input type="checkbox" id='swith-mus' unchecked><div class="slider"></div></label></td>
          <td>Broadcast</td>
          <td><label class="switch"><input type="checkbox" id='swith-bro' unchecked><div class="slider"></div></label></td></tr>
    </table>
    <table class='switch-tbl' id='tbl-org-size-switch'>
      <tr><td>Very Small</td>
          <td><label class="switch"><input type="checkbox" id='swith-vs' unchecked><div class="slider"></div></label></td>
          <td>Small</td>
          <td><label class="switch"><input type="checkbox" id='swith-sm' unchecked><div class="slider"></div></label></td></tr>
      <tr><td>Medium</td>
          <td><label class="switch"><input type="checkbox" id='swith-m' unchecked><div class="slider"></div></label></td>
          <td>Large</td>
          <td><label class="switch"><input type="checkbox" id='swith-l' unchecked><div class="slider"></div></label></td></tr>
      <tr><td>Very Large</td>
          <td><label class="switch"><input type="checkbox" id='swith-vl' unchecked><div class="slider"></div></label></td>
      </tr>
    </table>
  </div>
  <hr>
  <table id='tbl-org-searched'>
  </table>
  <table id='tbl-allorg'>
    <% @organizations.each do |organization| %>
      <tr id='row-<%= organization.id %>'>
        <td><%= organization.name %></td>
        <td><a href= '<%= organization_path(organization) %>' id='<%= organization.id %>'>More...</a></td>
      </tr>
    <% end %>
  </table>
</div>
<%= render :partial => 'legend' %>

app/views/organizations/show.html.erb
<div id='map-one-org'>
</div>

<div class="sidebar-one-org">
  <div class="col-md-12">
    <div id='btn-back'>
      <%= link_to 'Back',organizations_path, :id => 'link-back'%>
    </div>

  </div><br><br>

  <div class="col-md-12 panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          <h4><b>Organization Information</b></h4>
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <div>
          <h4><%= @organization.name %></h4>
        </div>
        <div>
          <table id='tbl-oneorg'>
            <tr>
              <td>Address</td>
              <td id='org-address'><%= @organization.address + ", " + @organization.city + ", " + @organization.state + "" + @organization.zip.to_s %></td>
            </tr>
            <tr>
              <td>Budget</td>
              <td id='org-size'><%= @organization.size %></td>
            </tr>
            <tr>
              <td>Type</td>
              <td id='org-type'><%= @organization.org_type %></td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          <h4><b>User Ratings</b></h4>
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        <div>
          <table id='tbl-oneorgrating'>
            <tr><td class='tbl-rating-colname'>Average Score:</td>
            <tr><td id='org-rating'><%= @average %></td></tr>
            <tr><td class='tbl-rating-colname'>The most recent comment:</td>
            <tr><td id='org-comment'><%= @comment %></td></tr>
          </table>
        </div><br>
        <div id='btn-comment'>
          <!-- <%= link_to 'Back',
                      organizations_path,
                      :class => 'btn-back' %> -->
          <%= link_to 'Comment',
                      new_organization_rating_path(@organization),
                      :class => 'btn-comment' %>
        </div><br>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          <h4><b>Find Nearby</b></h4>
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
        <div>
          <div><h4>Show Nearby&nbsp;&nbsp;<input type="checkbox" id='ck-nearby-restaurants'></h4></div>
          <div id='show-nearby'>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
              <li role="presentation" class="active" id='tab-res'><a href="#res" aria-controls="home" role="tab" data-toggle="tab">Restaurants</a></li>
              <li role="presentation" id='tab-bar'><a href="#bar" aria-controls="profile" role="tab" data-toggle="tab">Bars</a></li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
              <div role="tabpanel" class="tab-pane fade in active" id="res">
                <div id='yelp-restaurants'></div>
              </div>
              <div role="tabpanel" class="tab-pane fade" id="bar">
                <div id='yelp-bars'></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</div>

app/views/ratings/_form.html.erb
<%= form_for [@organization, @rating], :html => { :class => "form-horizontal rating" } do |f| %>

<% if @rating.errors.any? %>
  <div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h3>
    </div>
    <div class="panel-body">
      <ul>
      <% @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="form-group" style="margin: 30px 0 30px 0">
  <h4 style="margin:20px; padding: 20px;"><b><%= @rating.organization.name%></b></h4>
  <%= f.label :user_name, :class => 'control-label col-lg-2' %>
  <div class="col-lg-3">
    <%= f.text_field :user_name, :class => 'form-control' %>
  </div>
  <%=f.error_span(:user_name) %>
</div>
<div class="form-group" style="margin: 30px 0 30px 0">
  <%= f.label :score, :class => 'control-label col-lg-2' %>
  <div class="col-lg-5">
    <%= f.text_field :score, :class => 'form-control' %>
  </div>
  <%=f.error_span(:score) %>
</div>
<div class="form-group" style="margin: 30px 0 30px 0">
  <%= f.label :comment, :class => 'control-label col-lg-2' %>
  <div class="col-lg-6">
    <%= f.text_field :comment, :class => 'form-control' %>
  </div>
  <%=f.error_span(:comment) %>
</div>

<div class="form-group">
  <div class="col-lg-offset-2 col-lg-10">
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              organization_path(@rating.organization), :class => 'btn-cancel' %>
    <%= f.submit nil, :class => 'btn-submit' %>
  </div>
</div>

<% end %>

app/views/ratings/edit.html.erb
<%- model_class = Rating -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ratings/index.html.erb
<%- model_class = Rating -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_name) %></th>
      <th><%= model_class.human_attribute_name(:score) %></th>
      <th><%= model_class.human_attribute_name(:comment) %></th>
      <th><%= model_class.human_attribute_name(:organization_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= link_to rating.id, rating_path(rating) %></td>
        <td><%= rating.user_name %></td>
        <td><%= rating.score %></td>
        <td><%= rating.comment %></td>
        <td><%= rating.organization_id %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_rating_path(rating), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      rating_path(rating),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<!-- <%= link_to t('.new', :default => t("helpers.links.new")),
            new_rating_path,
            :class => 'btn btn-primary' %> -->

app/views/ratings/new.html.erb
<%- model_class = Rating -%>
<div class="page-header" style="padding-left: 20px;">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ratings/show.html.erb
<%- model_class = Rating -%>
<div class="page-header">
  <h1 style="padding-left:20px;"><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Organization Name:</strong></dt>
  <dd><%= @rating.organization.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_name) %>:</strong></dt>
  <dd><%= @rating.user_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:score) %>:</strong></dt>
  <dd><%= @rating.score %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comment) %>:</strong></dt>
  <dd><%= @rating.comment %></dd>
</dl>
<div style="padding: 20px;">
<%= link_to t('.back', :default => t("helpers.links.back")),
              organization_path(@rating.organization), :class => 'btn-back'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_rating_path(@rating), :class => 'btn-edit' %>
</div>